name: Generate All Repo Commit Heatmap

on:
  schedule:
    - cron: '0 0 * * *'  # 12 AM UTC daily
    - cron: '0 12 * * *' # 12 PM UTC daily
  push:
    # only trigger on branches, not on tags
    branches: '**'
  workflow_dispatch:

jobs:
  generate-heatmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Pull latest changes
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Run heatmap script
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GH_USERNAME: ${{ env.GH_USERNAME }}
        run: |
          python scripts/main.py

      - name: Fetch and Rebase Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin main
          git rebase origin/main
      -  name: Commit new Heatmap
         run: |
          git add assets/heatmap.png
          git commit -m "Update all-repo heatmap image"
          git push
          continue-on-error: true
